#
# Makefile for Bosch sensor driver.
#
obj-y  += fm17750_i2c.o
obj-y  += cpu_app.o
obj-y  += cpu_card.o
obj-y  += des.o
obj-y  += fm175xx.o
obj-y  += spi.o
obj-y  += type_a.o
obj-y  += spi.o
obj-y  += MIFARE.o
obj-y  += nfc_cmd_handle.o
obj-y  += READER_API.o
#EXTRA_CFLAGS += -DBMI160_ENABLE_INT1
#EXTRA_CFLAGS += -DBMI160_ENABLE_INT2
