#
# Makefile for Bosch sensor driver.
#
obj-y  += fm17750_i2c.o
obj-y  += FM175XX.o
obj-y  += MIFARE.o
obj-y  += READER_API.o
obj-y  += nfc_netlink.o
obj-y  += nfc_cmd_handle.o
#EXTRA_CFLAGS += -DBMI160_ENABLE_INT1
#EXTRA_CFLAGS += -DBMI160_ENABLE_INT2
